baseURL = "https://yourwebsitenamegoeshere.com/"
languageCode = "en-us"
title = "iXsystems™ Documentation"
theme = "aether"
#googleAnalytics = "Your google analytics tracking ID - optional"
#disqusShortname = "Your shortname for Disqus - optional"

[params]
  brand = "iXsystems™ Documentation"
  description = "One stop shop for iXsystems™ related docs."
  #homeimg = "URL to the image used for the home button at the bottom of each post - optional"
  #bgimg = "URL to the image used for the page background - optional"
  #rssinmenu = whether you would like a RSS feed link to appear in the navigation menu (true, false) - optional