name: Spell Check

on:
  push:
    branches:
      - master
  pull_request:
    branches:
    - master

jobs:
  setup-linux:
    name: setup-linux
    runs-on: ubuntu-latest
    - name: Spellcheck Action
      uses: rojopolis/spellcheck-github-actions@0.2.0
