name: Spell Check

on:
  push:
    branches:
      - master
  pull_request:
    branches:
    - master

jobs:
  spell-checking:
    runs-on: ubuntu-latest

    steps:
    - name: Spellcheck Action
      uses: rojopolis/spellcheck-github-actions@0.2.0
