name: Publish Docs

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Checkout Master
        uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - run: npm install -D --save autoprefixer
      - run: npm install -D --save postcss-cli

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2.2.1
        with:
          hugo-version: 'latest'
          extended: true

      - name: Prepare Hugo
        run: |
          git submodule sync && git submodule update -f --init
          
      - name: Build
        run: hugo -t docsy -d public --gc --minify --cleanDestinationDir
        
      - name: add nojekyll
        run: touch ./docs/public/.nojekyll
        
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v2.4.0
        with:
          emptyCommits: false
        env:
          ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: ./public
